export const DEFAULT_PAINTERS = [
  {
    name: 'Marek',
    email: 'mailhospodarsky@gmail.com',
    phone: '+420777650320',
    approx_location: 'Praha 2',
    experience_label: '30 let praxe',
    role: 'Byty a běžné výmalby',
    summary: 'Nejlépe sedí na klasické bytové zakázky, kde je důležitá pečlivá příprava a čistá práce.',
    price_label: '10 000–18 000 Kč',
    response_label: 'Volá do 20 min',
    jobs_label: '560 zakázek',
    image_url: 'uploads/marek.jpeg',
    image_position: 'center 0%',
    specialties: ['Byty', 'Běžná výmalba', 'Pečlivá příprava'],
    is_active: true,
    service_areas: ['Praha 2', 'Praha', 'Středočeský kraj'],
    work_types: ['Běžná bílá výmalba', 'Byty', 'Přemalby'],
    is_express_enabled: false,
    reliability_score: 4.8,
    notes: '',
  },
  {
    name: 'Vincent',
    email: 'vincent@malirhned.local',
    phone: '+420777650322',
    approx_location: 'Praha 4',
    experience_label: '5–7 let praxe',
    role: 'Novostavby a větší byty',
    summary: 'Sedí mu čisté zakázky, které se dají dobře naplánovat dopředu.',
    price_label: '14 000–25 000 Kč',
    response_label: 'Volá do 25 min',
    jobs_label: '198 zakázek',
    image_url: 'uploads/vincent.jpeg',
    image_position: 'center 0%',
    specialties: ['Novostavby', '3+kk a větší', 'Stropy'],
    is_active: true,
    service_areas: ['Praha 4', 'Praha', 'Středočeský kraj'],
    work_types: ['Novostavby', 'Stropy', 'Běžná bílá výmalba'],
    is_express_enabled: false,
    reliability_score: 4.7,
    notes: '',
  },
  {
    name: 'Martin',
    email: 'martin@malirhned.local',
    phone: '+420777650325',
    approx_location: 'Praha 5',
    experience_label: '3–5 let praxe',
    role: 'Přesné zakrytí a detail',
    summary: 'Víc než rychlost řeší pečlivost a čistý detail kolem nábytku nebo kuchyně.',
    price_label: '12 000–20 000 Kč',
    response_label: 'Volá do 31 min',
    jobs_label: '127 zakázek',
    image_url: 'uploads/martin.jpeg',
    image_position: 'center 0%',
    specialties: ['Detailní práce', 'Zakrytí nábytku', 'Barevné malby'],
    is_active: true,
    service_areas: ['Praha 5', 'Praha', 'Středočeský kraj'],
    work_types: ['Barevné malby', 'Detailní práce', 'Běžná bílá výmalba'],
    is_express_enabled: false,
    reliability_score: 4.8,
    notes: '',
  },
  {
    name: 'Lenka',
    email: 'lenka@malirhned.local',
    phone: '+420777650324',
    approx_location: 'Praha 3',
    experience_label: '3–5 let praxe',
    role: 'Rychlé termíny',
    summary: 'Když je potřeba rychle vymalovat menší byt nebo kancelář, umí se přizpůsobit tempu.',
    price_label: '7 500–15 000 Kč',
    response_label: 'Volá do 12 min',
    jobs_label: '173 zakázek',
    image_url: 'uploads/lenka.jpeg',
    image_position: 'center 0%',
    specialties: ['Menší byty', 'Kanceláře', 'Do 48 hodin'],
    is_active: true,
    service_areas: ['Praha 3', 'Praha', 'Středočeský kraj'],
    work_types: ['Běžná bílá výmalba', 'Kanceláře', 'Po nájemníkovi'],
    is_express_enabled: true,
    reliability_score: 4.6,
    notes: '',
  },
  {
    name: 'Albert',
    email: 'albert@malirhned.local',
    phone: '+420777650321',
    approx_location: 'Praha 6',
    experience_label: '5–7 let praxe',
    role: 'Po nájemníkovi a menší byty',
    summary: 'Nejčastěji maluje byty před nastěhováním a rychlé přemalby.',
    price_label: '9 000–16 000 Kč',
    response_label: 'Volá do 18 min',
    jobs_label: '286 zakázek',
    image_url: 'uploads/albert.jpeg',
    image_position: 'center 0%',
    specialties: ['Po nájemníkovi', '1+kk až 3+1', 'Rychlé termíny'],
    is_active: true,
    service_areas: ['Praha 6', 'Praha', 'Středočeský kraj'],
    work_types: ['Po nájemníkovi', 'Běžná bílá výmalba', 'Přemalby'],
    is_express_enabled: true,
    reliability_score: 4.9,
    notes: '',
  },
  {
    name: 'Pavel',
    email: 'pavel@malirhned.local',
    phone: '+420777650323',
    approx_location: 'Praha 9',
    experience_label: '3–5 let praxe',
    role: 'Přemalby a opravy',
    summary: 'Dělá běžné přemalby i stěny, které potřebují před malbou srovnat.',
    price_label: '8 000–18 000 Kč',
    response_label: 'Volá do 22 min',
    jobs_label: '244 zakázek',
    image_url: 'uploads/pavel.jpeg',
    image_position: 'center 0%',
    specialties: ['Opravy stěn', 'Přemalby', 'Starší byty'],
    is_active: true,
    service_areas: ['Praha 9', 'Praha', 'Středočeský kraj'],
    work_types: ['Opravy stěn', 'Přemalby', 'Běžná bílá výmalba'],
    is_express_enabled: true,
    reliability_score: 4.8,
    notes: '',
  },
]
