export const DEFAULT_PAINTERS = [
  {
    name: 'Petr Havel',
    email: 'petr.havel@malirhned.local',
    phone: '+420777650321',
    approx_location: 'Praha 6',
    experience_label: '12 let praxe',
    role: 'Po nájemníkovi a menší byty',
    summary: 'Nejčastěji maluje byty před nastěhováním a rychlé přemalby.',
    price_label: '9 000–16 000 Kč',
    response_label: 'Volá do 18 min',
    jobs_label: '286 zakázek',
    image_url: 'https://images.pexels.com/photos/4981775/pexels-photo-4981775.jpeg?auto=compress&cs=tinysrgb&w=300&h=300&fit=crop',
    specialties: ['Po nájemníkovi', '1+kk až 3+1', 'Rychlé termíny'],
    is_active: true,
    service_areas: ['Praha 6', 'Praha', 'Středočeský kraj'],
    work_types: ['Po nájemníkovi', 'Běžná bílá výmalba', 'Přemalby'],
    is_express_enabled: true,
    reliability_score: 4.9,
    notes: '',
  },
  {
    name: 'Martin Růžička',
    email: 'martin.ruzicka@malirhned.local',
    phone: '+420777650322',
    approx_location: 'Praha 4',
    experience_label: '14 let praxe',
    role: 'Novostavby a větší byty',
    summary: 'Sedí mu čisté zakázky, které se dají dobře naplánovat dopředu.',
    price_label: '14 000–25 000 Kč',
    response_label: 'Volá do 25 min',
    jobs_label: '198 zakázek',
    image_url: 'https://images.pexels.com/photos/7788241/pexels-photo-7788241.jpeg?auto=compress&cs=tinysrgb&w=300&h=300&fit=crop',
    specialties: ['Novostavby', '3+kk a větší', 'Stropy'],
    is_active: true,
    service_areas: ['Praha 4', 'Praha', 'Středočeský kraj'],
    work_types: ['Novostavby', 'Stropy', 'Běžná bílá výmalba'],
    is_express_enabled: false,
    reliability_score: 4.7,
    notes: '',
  },
  {
    name: 'Roman Veselý',
    email: 'roman.vesely@malirhned.local',
    phone: '+420777650323',
    approx_location: 'Praha 9',
    experience_label: '11 let praxe',
    role: 'Přemalby a opravy',
    summary: 'Dělá běžné přemalby i stěny, které potřebují před malbou srovnat.',
    price_label: '8 000–18 000 Kč',
    response_label: 'Volá do 22 min',
    jobs_label: '244 zakázek',
    image_url: 'https://images.pexels.com/photos/8961528/pexels-photo-8961528.jpeg?auto=compress&cs=tinysrgb&w=300&h=300&fit=crop',
    specialties: ['Opravy stěn', 'Přemalby', 'Starší byty'],
    is_active: true,
    service_areas: ['Praha 9', 'Praha', 'Středočeský kraj'],
    work_types: ['Opravy stěn', 'Přemalby', 'Běžná bílá výmalba'],
    is_express_enabled: true,
    reliability_score: 4.8,
    notes: '',
  },
  {
    name: 'David Svoboda',
    email: 'david.svoboda@malirhned.local',
    phone: '+420777650324',
    approx_location: 'Praha 3',
    experience_label: '8 let praxe',
    role: 'Rychlé termíny',
    summary: 'Když je potřeba rychle malovat menší byt nebo kancelář, umí se přizpůsobit tempu.',
    price_label: '7 500–15 000 Kč',
    response_label: 'Volá do 12 min',
    jobs_label: '173 zakázek',
    image_url: 'https://images.pexels.com/photos/3931131/pexels-photo-3931131.jpeg?auto=compress&cs=tinysrgb&w=300&h=300&fit=crop',
    specialties: ['Menší byty', 'Kanceláře', 'Do 48 hodin'],
    is_active: true,
    service_areas: ['Praha 3', 'Praha', 'Středočeský kraj'],
    work_types: ['Běžná bílá výmalba', 'Kanceláře', 'Po nájemníkovi'],
    is_express_enabled: true,
    reliability_score: 4.6,
    notes: '',
  },
  {
    name: 'Jakub Černý',
    email: 'jakub.cerny@malirhned.local',
    phone: '+420777650325',
    approx_location: 'Praha 5',
    experience_label: '10 let praxe',
    role: 'Přesné zakrytí a detail',
    summary: 'Víc než rychlost řeší pečlivost a čistý detail kolem nábytku nebo kuchyně.',
    price_label: '12 000–20 000 Kč',
    response_label: 'Volá do 31 min',
    jobs_label: '127 zakázek',
    image_url: 'https://images.pexels.com/photos/10682438/pexels-photo-10682438.jpeg?auto=compress&cs=tinysrgb&w=300&h=300&fit=crop',
    specialties: ['Detailní práce', 'Zakrytí nábytku', 'Barevné malby'],
    is_active: true,
    service_areas: ['Praha 5', 'Praha', 'Středočeský kraj'],
    work_types: ['Barevné malby', 'Detailní práce', 'Běžná bílá výmalba'],
    is_express_enabled: false,
    reliability_score: 4.8,
    notes: '',
  },
]
